name: Compile Rkt Expander Linklet

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  gen-expander:
    runs-on: ubuntu-18.04
    container: racket/racket:latest

    steps:
      - run: apt-get update && apt-get install -y git build-essential
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ACTION_TOKEN }}
      - run: racket --version
      - run: git clone --depth=1 https://github.com/racket/racket
      - working-directory: ./racket/
        run: make fetch-pb
      - working-directory: ./racket/racket/src/
        run: |
          ./configure
          make -j$(nproc)
          make -j$(nproc) install
      - working-directory: ./racket/racket/src/expander
        run: ../../bin/racket -N raco -l- raco pkg install --auto compiler-lib
      - working-directory: ./racket/racket/src/expander
        run: make expander-src
      - run: |
          mkdir -p expander
          cp racket/racket/src/expander/compiled/expander.rktl expander/
      - if: ${{ env.ACT != 'true' }}
        uses: EndBug/add-and-commit@v7
        with:
          add: 'expander/expander.rktl'
          author_name: 'Paulo Matos (via GH Action)'
          author_email: 'p@ocmatos.com'
          message: 'Update expander linklet'
          push: true
        
